param(
  [string]$Source = "manuscript.tex",
  [string]$Output = "manuscript_single.tex"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$Utf8 = [System.Text.UTF8Encoding]::new($false)

function Resolve-TexPath {
  param(
    [string]$BaseDir,
    [string]$InputPath
  )

  $candidate = Join-Path $BaseDir $InputPath
  if (-not ($candidate.EndsWith(".tex"))) {
    $candidate = "$candidate.tex"
  }
  return (Resolve-Path $candidate).Path
}

function Expand-TexFile {
  param(
    [string]$FilePath,
    [System.Collections.Generic.HashSet[string]]$Stack
  )

  $fullPath = (Resolve-Path $FilePath).Path
  if ($Stack.Contains($fullPath)) {
    throw "Detected circular \\input chain at: $fullPath"
  }

  [void]$Stack.Add($fullPath)
  $baseDir = Split-Path $fullPath -Parent
  $lines = [System.IO.File]::ReadAllLines($fullPath, $Utf8)
  $out = New-Object System.Collections.Generic.List[string]

  foreach ($line in $lines) {
    if ($line -match '^\s*\\input\{([^}]+)\}\s*$') {
      $rel = $matches[1]
      $target = Resolve-TexPath -BaseDir $baseDir -InputPath $rel
      $out.Add("% --- Begin input: $rel ---")
      $expanded = Expand-TexFile -FilePath $target -Stack $Stack
      foreach ($l in $expanded) { $out.Add($l) }
      $out.Add("% --- End input: $rel ---")
    }
    else {
      $out.Add($line)
    }
  }

  [void]$Stack.Remove($fullPath)
  return $out
}

$sourcePath = (Resolve-Path $Source).Path
$stamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$header = @(
  "% Auto-generated single-file manuscript",
  "% Source: $Source",
  "% Generated at: $stamp",
  "% Do not edit this file directly; edit manuscript.tex and chapters/*.tex instead.",
  ""
)

$stack = New-Object 'System.Collections.Generic.HashSet[string]'
$content = Expand-TexFile -FilePath $sourcePath -Stack $stack
$all = $header + $content

[System.IO.File]::WriteAllLines($Output, $all, $Utf8)
Write-Host "Generated $Output from $Source"
